// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
void rcpp_hello_world();
RcppExport SEXP nabo_rcpp_hello_world() {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        rcpp_hello_world();
    }
    return R_NilValue;
END_RCPP
}
