// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// knn_cpp
List knn_cpp(const Eigen::Map<Eigen::MatrixXd> data, const Eigen::Map<Eigen::MatrixXd> query, const int k, const double eps = 0.0);
RcppExport SEXP nabo_knn_cpp(SEXP dataSEXP, SEXP querySEXP, SEXP kSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type data(dataSEXP );
        Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type query(querySEXP );
        Rcpp::traits::input_parameter< const int >::type k(kSEXP );
        Rcpp::traits::input_parameter< const double >::type eps(epsSEXP );
        List __result = knn_cpp(data, query, k, eps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// knn_brute_cpp
List knn_brute_cpp(const Eigen::Map<Eigen::MatrixXd> data, const Eigen::Map<Eigen::MatrixXd> query, const int k);
RcppExport SEXP nabo_knn_brute_cpp(SEXP dataSEXP, SEXP querySEXP, SEXP kSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type data(dataSEXP );
        Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type query(querySEXP );
        Rcpp::traits::input_parameter< const int >::type k(kSEXP );
        List __result = knn_brute_cpp(data, query, k);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
