# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_generic <- function(st, data, query, k, eps, radius) {
    .Call('_nabor_knn_generic', PACKAGE = 'nabor', st, data, query, k, eps, radius)
}

